apiVersion: v1
kind: Service
metadata:
  name: owncloud
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: owncloud
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: mariadb
  selector:
    app: mariadb